global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: critical-alerts
      continue: true
    - match:
        severity: warning
      receiver: warning-alerts

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://backend:3000/api/monitoring/alerts'
        send_resolved: true

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://backend:3000/api/monitoring/alerts/critical'
        send_resolved: true
    
  - name: 'warning-alerts'
    webhook_configs:
      - url: 'http://backend:3000/api/monitoring/alerts/warning'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']