name: Progression System Tests

on:
  push:
    branches: [ main, develop, 'integration/*' ]
    paths:
      - 'backend/**'
      - '.github/workflows/test-progression.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'

jobs:
  test-progression:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: quiz_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install dependencies
      working-directory: ./backend
      run: npm ci
    
    - name: Setup test environment
      working-directory: ./backend
      run: |
        cp .env.example .env.test
        echo "DB_HOST=localhost" >> .env.test
        echo "DB_USER=postgres" >> .env.test
        echo "DB_PASSWORD=postgres" >> .env.test
        echo "DB_NAME=quiz_test" >> .env.test
        echo "REDIS_HOST=localhost" >> .env.test
        echo "NODE_ENV=test" >> .env.test
    
    - name: Run migrations
      working-directory: ./backend
      env:
        NODE_ENV: test
      run: npm run migrate
    
    - name: Start server
      working-directory: ./backend
      env:
        NODE_ENV: test
      run: |
        npm start &
        sleep 5
    
    - name: Run TDD tests
      working-directory: ./backend
      run: npm run test:tdd
    
    - name: Run progression tests
      working-directory: ./backend
      run: npm run test:progression
    
    - name: Run integration tests
      working-directory: ./backend
      run: npm run test:integration || true
    
    - name: Verify demo
      working-directory: ./backend
      run: npm run verify